apiVersion: operator.vault.banzaicloud.com/v1alpha1
kind: OperatorConfig
metadata:
  name: operatorconfig-sample
spec:
  # Default values copied from <project_dir>/helm-charts/vault-operator/values.yaml
  affinity: {}
  crdAnnotations: {}
  fullnameOverride: ""
  image:
    bankVaultsRepository: ghcr.io/banzaicloud/bank-vaults
    imagePullSecrets: []
    pullPolicy: IfNotPresent
    repository: ghcr.io/banzaicloud/vault-operator
  labels: {}
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  nameOverride: ""
  podLabels: {}
  priorityClassName: ""
  psp:
    enabled: false
    vaultSA: vault
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    externalPort: 80
    internalPort: 8080
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: true
    name: ""
  syncPeriod: 1m
  terminationGracePeriodSeconds: 10
  watchNamespace: ""
  
  
