name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-bin
          path: ./bin

      - id: meta
        name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/3scale/bank-vaults-helm-operator
          tags: |
            type=semver,pattern={{raw}}

      - id: meta-bundle
        name: Docker meta for the bundle image
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/3scale/bank-vaults-helm-operator-bundle
          tags: |
            type=semver,pattern={{raw}}

      - id: meta-catalog
        name: Docker meta for the catalog image
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/3scale/bank-vaults-helm-operator-catalog
          tags: |
            type=semver,pattern={{raw}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Export release name
        run: |
          echo "NEW_RELEASE=$(make get-new-release)" >> $GITHUB_ENV

      - name: Login to quay.io/3scale
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: quay.io
          username: ${{ secrets.REGISTRY_USER }}

      - name: Donwload helm chart
        run: make download-helm-chart

      - name: Build and push operator
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Build and push bundle
        uses: docker/build-push-action@v6
        with:
          file: bundle.Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Generate catalog Dockerfile
        run: make catalog-generate

      - name: Build and push catalog
        uses: docker/build-push-action@v6
        with:
          file: catalog.Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Create a new draft-release in github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: ${{ steps.meta.outputs.tags }}
          draft: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: ${{ steps.meta.outputs.tags }}
